### PR TITLE
feat: xmtp

### PR DESCRIPTION
**Pull request by humanagent**
Integrating xmtp + paymentagent demo

### CODE REVIEW

**Comment by humanagent** [comment]
hey @shakkernerd im Fabri from XMTP

How would i proceed to let you know when i completed the demo? OR something i should consider?

**Comment by humanagent** [comment]
Hey! Just submitted a working demo with the 3 pieces. 

Let me know what i need to improve the PR please 🙏🏻

**Comment by shakkernerd** [comment]
Hi @humanagent I will look into these.
Thanks for submitting a demo.
Could you perhaps resolve the conflicts?

**Comment by humanagent** [comment]
Thks! Would a video help?

I been trying to merge but cant get those conflicts to go away. 

Im doing 

```
 git merge origin/develop
 
abrizioguespe@fabrizios-MacBook-Pro eliza %   git merge origin/develop
Auto-merging agent/src/index.ts
CONFLICT (content): Merge conflict in agent/src/index.ts
Auto-merging packages/core/src/types.ts
Auto-merging pnpm-lock.yaml
CONFLICT (content): Merge conflict in pnpm-lock.yaml
Automatic merge failed; fix conflicts and then commit the result.
```


CleanShot 2024-12-24 at 08 32 45@2x

**Comment by shakkernerd** [comment]
@humanagent By video, do you mean a video of the demo? If yes, that'll be dope!

As for the conflicts, I'll see what I can do from my end.

**Comment by humanagent** [comment]
On it! I'm thinking a deep dive into plugins would be cool im seeing some content online but not going deep overall.

Cont here: https://github.com/elizaOS/eliza/pull/1441

I think should be resolved now. Did an update. couldnt fix the current.

**Pull request closed without merging**
