### PR TITLE
chore: update env for plugin-goat

### PR DESCRIPTION
**Pull request by aeither**
# Relates to:

# Risks

# Background

## What does this PR do?

Update ALCHEMY_API_KEY to EVM_PROVIDER_URL for plugin-goat
which is more accurate as user can provide any rpc URL. it is not an alchemy api key what needs to be provided

## What kind of change is this?

# Documentation changes needed?

# Testing

### CODE REVIEW

**Review by odilitime — DISMISSED** [review]
Will need to update the documentation

**Comment by aeither** [comment]
> Will need to update the documentation

Where?

**Comment by odilitime** [comment]
search the repo for any mention of ALCHEMY_API_KEY

if none, at a bare minimum include the instructions of the plugin README

**Review by monilpat — APPROVED** [review]
LGTM

**Pull request merged**
