### PR TITLE
feat: Add agentic JSDoc generation  

### PR DESCRIPTION
**Pull request by Ed-Marcavage**
# Relates to:
- https://github.com/ai16z/eliza/issues/1110

# Risks:
- [Minimal risk](https://github.com/AudixAI/eliza/pull/61/files#diff-161a3b9e158608637126680e24d9da26490263370a9e6a63479fe9b42bd4a4f3R92): Sometimes it adds an extra astrict in the JSDoc requiring a human to pull the branch locally and remove it, an example is linked. 

# Background

## What does this PR do?
- The codebase includes a GitHub Actions workflow (`JSDoc Automation`) that allows triggering the documentation generation process with custom parameters. The workflow is defined in the `.github/workflows` directory.

## What kind of change is this?
- Features: LLM Based JSDoc generator

## Why are we doing this? Any context or related work?
- https://github.com/ai16z/eliza/issues/1110

# Documentation changes needed?
- Not needed - already generated

# Testing
- https://github.com/AudixAI/eliza/pull/61/files
- https://github.com/AudixAI/eliza/pull/60/files
## Where should a reviewer start?
- packages/jsdoc-automation/src/index.ts

## Detailed testing steps
###Configure and trigger the workflow manually
- The workflow can be triggered manually using the `workflow_dispatch` event, which accepts the following inputs:
- `pull_number` (optional): The pull request number to generate documentation for.
  - if not provided, the `root_directory` will be scanned
  - PR must be merged to develop/main branch
- `root_directory` (required): Only scans files in this directory.
  - Description: Target directory relative to repository root (e.g., packages/core/src)
  - Default: `packages/core/src/test_resources` - arbitrarily chose this because its small
- `excluded_directories` (required): Directories to exclude from scanning.
  - Description: Comma-separated list of directories to exclude, relative to root_directory
  - Default: 'node_modules,dist,test'
- `reviewers` (required): Pull Request Reviewers.
  - Description: Comma-separated list of GitHub usernames
  - Default: ''
 
### Set up
- Set GH_PAT & OPENAI_API_KEY in github actions as secret env variables

# Deploy Notes
- Set GH_PAT & OPENAI_API_KEY in github actions as secret env variables

## Discord username
- 0xbuildinpublic

### CODE REVIEW

**Comment by odilitime** [comment]
Hrm it's not really a plugin but lives in the plugins directory... Probably wouldn't take much work to convert to a plugin

**Comment by Ed-Marcavage** [comment]
I am happy to convert it to a plugin; just let me know, I am not sure if it makes sense as a plugin because it is currently invoked by GH Actions, not an agent, but I could see it being invoked by an agent in the future

**Comment by Ed-Marcavage** [comment]
After giving it more thought, I think I'm going to convert it to a plug in. I think it would be dope if you could be developing locally and just prompt eliza "generate documentation for ____" and then this code is executed - automatically generating documentation for the provided directory. 

Im going to try and make it executable via GH workflows and if an agent invokes it.

**Review by madjin — APPROVED** [review]
Awesome work, thanks for moving to scripts folder for now - after making it an eliza plugin can move to packages folder. Excited to use this.

We can tweak in the future based on feedback of the generated API docs + how people feel about the comments in the code (incase they're distracting). Will look into getting this working with correct github token soon. Great contribution!

**Pull request merged**
