### PR TITLE
fix: Duplicate twitter posts.

### PR DESCRIPTION
**Pull request by ChristopherTrimboli**
# Relates to:

https://github.com/ai16z/eliza/issues/1284

# Risks

LOW - could miss a post, or post less, but seems posting once correctly now on server boot.

# Background

## What does this PR do?

This PR fixes duplicate Twitter posts on Eliza server boot.

I think this was a mistake from a revert last week, can see git blame:

image

`generateNewTweetLoop()` is being ran twice with no conditionals on `post.start()`

## What kind of change is this?

Bug fixes (non-breaking change which fixes an issue)

## Why are we doing this? Any context or related work?

Twitter agents should not duplicate post on boot.

# Documentation changes needed?

My changes do not require a change to the project documentation.

# Testing

Before boot, see duplicates, after changes, only 1 post:

Screenshot From 2024-12-21 03-19-29

## Where should a reviewer start?

Try boot twitter agent with fresh delay, note no duplicate posts.

## Detailed testing steps

Start with fresh twitter account, no delay, boot server, look at profile timeline for duplicate posts.

## Discord username

cjft

### CODE REVIEW

**Comment by ChristopherTrimboli** [comment]
Integration test failing due to non PR issue in CI:

```
Run echo "Skipping integration tests due to missing required API keys"
Skipping integration tests due to missing required API keys
```

**Review by oxSaturn — APPROVED** [review]
lgtm.

**Comment by ChristopherTrimboli** [comment]
yoinked in: https://github.com/ai16z/eliza/pull/1339 :')

**Review by tcm390 — APPROVED** [review]

**Review by odilitime — APPROVED** [review]

**Comment by monilpat** [comment]
Closing as contained in another PR

**Pull request closed without merging**
