### PR TITLE
chore: format package.json files with prettier

### PR DESCRIPTION
**Pull request by ryanleecode**
Runs prettier on all package json files. This will make reviewing https://github.com/elizaOS/eliza/pull/1365 easier.

### CODE REVIEW

**Review by twilwa — APPROVED** [review]

**Comment by ryanleecode** [comment]
@twilwa why was this basically reverted in the most recent release?

**Comment by shakkernerd** [comment]
Hi @ryanleecode it was not reverted. The script that handles the version changes in the package.json files reformats the files.

**Comment by ryanleecode** [comment]
> Hi @ryanleecode it was not reverted. The script that handles the version changes in the package.json files reformats the files.

If the script formats using prettier, then it should be 4 spaces, since that was the point of this pr in the first place.

**Comment by shakkernerd** [comment]
#1573

**Pull request merged**
