### PR TITLE
fix: Double Responses from Continue Action

### PR DESCRIPTION
**Pull request by azep-ninja**
# Relates to:

# Risks

Low

# Background

## What kind of change is this?

Bug fixes (non-breaking change which fixes an issue)

This PR fixes a double response issue that was caused by the CONTINUE action in the plugin-bootstrap. The agent would respond to the same message multiple time due to the continue trigger.

# Documentation changes needed?

N/A

# Testing

## Detailed testing steps

Test sending a message, watch logs for CONTINUE message to be triggered, watch logs as agent logs that a response has already been sent to an existing message or not responding further.

The double response was seen as triggered in a CONTINUE action whe the agent would ask/frame response a certain way back to the user. Which on subsequent messages, would trigger the callback to respond to the same message multiple times.

Where the continue action is meant for a natural flow of thoughts to keep generating, on normal back and forth convo's it would duplicate response.

Fix below now stops that as it takes into consideration its own message it just responded to, and how it framed to either not respond again, or continue a thought as it was intended.

---TESTING Screen Record---
1st section shows a previous double response, which is triggered by the question the agent asked to the user, which in turn triggers a double response on the next reply from the user

2nd section shows continue being triggered as normal, but not triggering another response in the handler callback since it already responded. This will still allow continue to allow the agent to "continue" a thought it had as it was intended, also, per the examples.

https://github.com/user-attachments/assets/0ed92c8f-dc99-4c3b-95fc-9c0052f56197

# Deploy Notes

## Discord username
ninja_dev

### CODE REVIEW

**Review by monilpat — CHANGES_REQUESTED** [review]
Thanks so much for doing this can you please add a test (screengrab works) that this actually resolved the double response issue - it LGTM but want to confirm thanks :)

**Comment by azep-ninja** [comment]
@monilpat heres a screen grab.

1st section shows a previous double response, which is triggered by the question the agent asked to the user, which in turn triggers a double response on the next reply from the user

2nd section shows continue being triggered as normal, but not triggering another response in the handler callback since it already responded. This will still allow continue to allow the agent to "continue" a thought it had as it was intended, also, per the examples.

https://github.com/user-attachments/assets/0ed92c8f-dc99-4c3b-95fc-9c0052f56197

**Review by monilpat — DISMISSED** [review]
Looks good to me thanks for the thorough testing :)

**Comment by monilpat** [comment]
It looks like unrelated changes are causing issues. Do you mind running the following command

To see if it happens locally
pnpm build

If it does run and resubmit 
pnpm i -r --no-frozen-lockfile

**Comment by azep-ninja** [comment]
> It looks like unrelated changes are causing issues. Do you mind running the following command
> 
> To see if it happens locally pnpm build
> 
> If it doesn't run and resubmit pnpm i -r --no-frozen-lockfile

Did a re-build, and confirmed it started up locally without issues, and re-pushed.

**Review by monilpat — APPROVED** [review]
LGTM

**Comment by Mr-Don-Leo** [comment]
This is a good fix, prior it was an issue of boredom. However, the added conditions and checks were pretty good.

**Pull request merged**
