### PR TITLE
fix: Update speech.ts

### PR DESCRIPTION
**Pull request by y4my4my4m**
# Relates to:

fixes https://github.com/ai16z/eliza/issues/1265

# Risks

# Background

## What does this PR do?

Allows elevenlabs audio to play in discord voice channel

## What kind of change is this?

# Documentation changes needed?

# Testing

### CODE REVIEW

**Comment by y4my4my4m** [comment]
Btw i recommend this model for best speed: `eleven_flash_v2_5`

**Review by monilpat — APPROVED** [review]
LGTM

**Comment by monilpat** [comment]
Any testing that can be done to confirm this works even just a screenshot?

**Comment by y4my4my4m** [comment]
@monilpat sorry, are you asking me to provide a screenshot or do you want a 3rd party tester?

**Review by odilitime — APPROVED** [review]

**Pull request merged**
