### PR TITLE
feat: handle long tweet

### PR DESCRIPTION
**Pull request by tcm390**
related: 
https://github.com/ai16z/eliza/issues/1178

This PR handles long tweets as follows:

1. Check if the post is a long post. If it’s not, proceed with a normal tweet. Otherwise, use the sendNoteTweet method for long tweets.
2. If sendNoteTweet fails, truncate the post and fall back to using a normal tweet.

test result: 

1. non-verfied user post: https://x.com/IBGDRGNAI/status/1870505476284469692
2. verified user post: https://x.com/JayChou11879/status/1870505908834615527

### CODE REVIEW

**Review by odilitime — COMMENTED** [review]
Code LGTM, important fix in there too

**Comment by odilitime** [comment]
duplicate of #1335

**Comment by odilitime** [comment]
Duplicate of #1329 too?

**Comment by tcm390** [comment]
> Duplicate of #1329 too?

Yes @ChristopherTrimboli already had a pr to fix double tweet issue. We should open his pr and merge his pr first

**Comment by ChristopherTrimboli** [comment]
> > Duplicate of #1329 too?
> 
> Yes @ChristopherTrimboli already had a pr to fix double tweet issue. We should open his pr and merge his pr first

im fine, I discussed with TCM, honest mistake, in open-source some saltiness if devs get PRs yoinked, but was legit coincidence, idc that much, just a 1 liner. I feel welcome after TCM chat + role upgrade, not worried.

**Comment by tcm390** [comment]
resolved conflict and tested

verified account: https://x.com/JayChou11879/status/1872688847106044244
non-verified-account: https://x.com/IBGDRGNAI/status/1872689915114475839

**Review by shakkernerd — APPROVED** [review]

**Pull request merged**
